
services:

  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8088:80
    working_dir: ${APP_PATH_CONTAINER}
    user: 1000:1000


  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345678
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    user: 1000:1000

  adminer:
    image: adminer
    restart: always
    ports:
      - 6088:8080

  composer:
    image: composer:2.7
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install

